spring.application.name=story-arc
spring.datasource.url=jdbc:mysql://localhost:3306/story_arc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis Plus
# mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml

# Initialize schema
spring.sql.init.mode=always
